HostInfo: reduce mutex.Locks
scylladb/gocql pull request #165
Opened 2024-04-08 10:56 UTC by moguchev

I know that there is comment by @zariel to reduce locking.

I didn't thoroughly refactor the code, but I found fast and cheap optimization in functions `(*HostInfo).HostName` and `(*HostInfo).HostNameAndPort`.

In our case of https://github.com/scylladb/gocql/pull/164 `(*HostInfo).HostName` leads to spending a lot of time in Lock...
Also in `QueryObserver` and `BatchObserver` we calls public methods of `HostInfo` (`HostName` ,  `HostNameAndPort`) for metrics and we have a lot of mutex locks.

2024-05-10 07:45 UTC, sylwiaszunejko requested changes

2024-05-10 07:45 UTC, sylwiaszunejko commented on host_source.go
> +	// Fast path: in 99.9% hostname is not empty
How did you deduce this number?

2024-05-10 07:45 UTC, sylwiaszunejko commented on host_source.go
> +	// Fast path: in 99.9% hostname is not empty
Same as before

2024-05-10 07:45 UTC, sylwiaszunejko commented on host_source.go
> +	return net.JoinHostPort(addr.String(), strconv.Itoa(h.port))
Not related to this PR, should not be here

2024-05-15 20:05 UTC, moguchev commented on host_source.go
> +	// Fast path: in 99.9% hostname is not empty
99.9% is certainly a big number.

We actively use the public methods `Hostname()` and `HostnameAndPort()` in `metrics.QueryObserver`. Accordingly, for each request in scylladb we call `Hostname()/HostnameAndPort()`, but if the cluster is stable and no reccconections occur, then hostname in most cases is not empty.

I'll attach go profile of mutex (before -> after) later

2024-05-16 21:08 UTC, roydahan commented
Please add a descriptive commit message to your commit.

2024-05-17 15:07 UTC, moguchev commented on host_source.go
> +	// Fast path: in 99.9% hostname is not empty
Before patch: 
<img width="1450" alt="Снимок экрана 2024-05-17 в 17 00 34" src="https://github.com/scylladb/gocql/assets/32189038/93863634-1631-4f20-8772-01d8863b0823">

2024-05-17 15:08 UTC, moguchev commented on host_source.go
> +	// Fast path: in 99.9% hostname is not empty
After: 
<img width="1447" alt="Снимок экрана 2024-05-17 в 17 00 45" src="https://github.com/scylladb/gocql/assets/32189038/38f50d27-64c8-4213-b656-7920dd2bac4e">

2024-06-02 15:26 UTC, dkropachev commented
I would recommend to use `atomic.Pointer` instead, please take a look [this paper](https://github.com/go-auxiliaries/perf-geek/blob/main/state-consistency/README.md#3-use-atomic-pointer-to-a-state-with-mutex-to-negate-state-submitting-collisions)

Since `HostInfo` experiance mostly read access, referred solution is going to be up to `90 times` faster than this one.

2024-06-10 06:28 UTC, mykaul commented
@moguchev - can you refresh the PR, addressing above comments?

2024-06-10 07:03 UTC, moguchev commented
> @moguchev - can you refresh the PR, addressing above comments?

Yes, I’ll do it

2024-06-13 03:23 UTC, dkropachev commented
@moguchev , I have given a try to `atomic update`, it is too intrusive and is going to create lot's of conflict with `upstream`, so it is better not to do that

2024-06-19 14:05 UTC, dkropachev approved these changes

2024-06-20 05:53 UTC, sylwiaszunejko approved these changes

2024-06-20 05:56 UTC, merged

2024-06-20 07:22 UTC, mykaul commented
Thanks @moguchev for your contribution!