Add github workflow running jenkins job
scylladb/gocql pull request #260
Opened 2024-09-13 08:17 UTC by sylwiaszunejko

This workflow pushes scylla-bench docker image using gocql version from the PR and triggers jenkins job that uses this image of scylla-bench.

2024-09-13 08:22 UTC, sylwiaszunejko commented
New workflow won't be running in CI in this PR, because it uses `pull_request_target` event. In this PR we can see how it behaves: https://github.com/scylladb/gocql/pull/255. 

Things to be changed:
- change jenkins_client fork to scylladb
- change user from me to some official jenkins user
- move jenkins job to official location

2024-09-13 13:00 UTC, dkropachev requested changes

2024-09-15 13:00 UTC, sylwiaszunejko commented on .github/workflows/extended-ci-asymmetric-cluster.yml
> +          ref: ${{ github.event.pull_request.head.ref }}
it seems to be not, look: https://github.com/scylladb/gocql/pull/255/checks
Or do you mean I should add `path: gocql` in some other place?

2024-09-16 08:22 UTC, sylwiaszunejko commented on .github/workflows/extended-ci-asymmetric-cluster.yml
> +          docker build -f ../gocql/.github/workflows/Dockerfile . -t ${SCYLLA_BENCH_DOCKER_IMAGE} --build-arg version=$SCYLLA_BENCH_VERSION
https://github.com/scylladb/scylla-bench/pull/143

2024-09-16 13:07 UTC, sylwiaszunejko commented
I went with @Lorak-mmk advice https://github.com/scylladb/gocql/issues/204#issuecomment-2352727699 
Now the changes are here:  https://github.com/scylladb/gocql/pull/255 and here we can see the new workflow running: https://github.com/scylladb/gocql/pull/263
Please move to these two PR with all discussions

2024-09-16 13:07 UTC, closed without merging