Add workflow to delete old docker images
scylladb/gocql pull request #268
Opened 2024-09-18 06:56 UTC by sylwiaszunejko

2024-09-18 06:59 UTC, sylwiaszunejko commented
Not sure how to test it, I put small number of days to actually have some images to remove for testing purpose

2024-09-18 08:02 UTC, dkropachev requested changes

2024-09-18 08:02 UTC, dkropachev commented on .github/workflows/clean_dockerhub_images.yml
> +                    delete_tag(DOCKERHUB_USERNAME, REPO_NAME, tag["name"], DOCKERHUB_TOKEN)
Great job on doing that, but I don't think we need to respect repo tags here.
What we should do is to find docker images by distinctive name, check if `last_pushed` from tags api response is past given date and clean it up if it is.

2024-09-18 08:02 UTC, dkropachev commented on .github/workflows/clean_dockerhub_images.yml
> +        from datetime import datetime, timedelta
Let's move all this code into a file in `scripts` or `ci` directory.
Create and `Makefile` to call it.

2024-09-18 08:24 UTC, sylwiaszunejko commented on .github/workflows/clean_dockerhub_images.yml
> +        clean_old_images()
and this `make clean-old-temporary-docker-images` should be run int the github action workflow similar to the one I wrote? Or we should just have the possibility to run it manually?

2024-09-18 09:32 UTC, dkropachev commented on .github/workflows/clean_dockerhub_images.yml
> +        clean_old_images()
You should run it instead of having these code, you will have only:
```
make clean-old-temporary-docker-images
```

2024-09-18 10:07 UTC, dkropachev approved these changes

2024-09-18 10:12 UTC, sylwiaszunejko commented
@dkropachev how can we test it? Do you have any idea?

2024-09-18 10:27 UTC, dkropachev commented
> @dkropachev how can we test it? Do you have any idea?

Sure, we need to kick out CICD for https://github.com/scylladb/gocql/pull/263 to publish an image, and then drop `DELETE_AFTER_DAYS` to -1 and run the script

2024-09-18 10:29 UTC, sylwiaszunejko commented
>Sure, we need to kick out CICD for https://github.com/scylladb/gocql/pull/263 to publish an image, which we already did and then drop DELETE_AFTER_DAYS to -1 and run the script

I meant the last part, how to run this script without merging this PR?

2024-09-18 10:47 UTC, dkropachev commented
> > Sure, we need to kick out CICD for #263 to publish an image, which we already did and then drop DELETE_AFTER_DAYS to -1 and run the script
> 
> I meant the last part, how to run this script without merging this PR?

Run it as part of CICD, temporary add :
```
on:
  pull_request_target
```

to the workflow.

2024-09-18 10:49 UTC, dkropachev requested changes

2024-09-18 10:49 UTC, dkropachev commented on ci/clean-old-temporary-docker-images.py
> +    return response.json()["results"]
Please hande bad response gracefully
```suggestion
        if response.status_code != 200:
        print(f"Failed to get tags, Status Code: {response.status_code}, {response.text}")
        return []
    return response.json()["results"]
```

2024-09-18 10:49 UTC, dkropachev commented on ci/clean-old-temporary-docker-images.py
> +    threshold_date = datetime.now() - timedelta(days=DELETE_AFTER_DAYS)
```suggestion
    threshold_date = datetime.now() - timedelta(days=int(DELETE_AFTER_DAYS))
```

2024-09-18 10:53 UTC, dkropachev commented on ci/clean-old-temporary-docker-images.py
> +import os
Or maybe do something like this:
```
import os
import requests
from datetime import datetime, timedelta

DOCKERHUB_TOKEN = os.environ["DOCKERHUB_TOKEN"]
DELETE_AFTER_DAYS = os.environ["DELETE_AFTER_DAYS"]

def get_repo_tags(token):
    url = f"https://hub.docker.com/v2/repositories/scylladb/gocql-extended-ci/tags/"
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        print(f"Failed to get tags, Status Code: {response.status_code}, {response.text}")
        return None
    return response.json()["results"]

def delete_tag(tag, token):
    url = f"https://hub.docker.com/v2/repositories/scylladb/gocql-extended-ci/tags/{tag}/"
    headers = {"Authorization": f"Bearer {token}"}
    response = requests.delete(url, headers=headers)
    if response.status_code > 200 and response.status_code < 300:
        print(f"Deleted tag: {tag}")
        return True
    print(f"Failed to delete tag: {tag}, Status Code: {response.status_code}")
    return False

def clean_old_images():
    tags = get_repo_tags(DOCKERHUB_TOKEN)
    if tags is None:
        return False
    threshold_date = datetime.now() - timedelta(days=int(DELETE_AFTER_DAYS))
    status = True
    for tag in tags:
        last_pushed = datetime.strptime(tag["last_pushed"], "%Y-%m-%dT%H:%M:%S.%fZ")
        if last_pushed < threshold_date:
            status = status and delete_tag(tag["name"], DOCKERHUB_TOKEN)
    return status

if __name__ == "__main__":
    if not clean_old_images():
        exit(1)
    exit(0)
```

To see when it fails

2024-09-19 09:59 UTC, sylwiaszunejko commented
Created PR from the repo branch to be able to run the workflow https://github.com/scylladb/gocql/pull/269

2024-09-19 09:59 UTC, closed without merging