fix `bigint` marshal, unmarshall
scylladb/gocql pull request #291
Opened 2024-10-03 21:42 UTC by illia-li

Fixed for `bigint` type:
1. `string` marshal and unmarshal as `nullable`. 
1.1. Before: marshals `""` - caused an error; unmarshals `nil data` into `"0"`.
1.2. Now: marshals and unmarshals `nil data` - `""`.
2. `custom string` marshals and unmarshals, before `not supported`, now `supported`.
3. `big.Int` marshals, before `not supported`, now `supported`.
4. Marshal data, which equal `math.MaxUint64`, into `uint64`, `uint`, return `error' before, now `no error`.
5. Unmarshall `data` with the length is different from `0` and `4`, did not return `error` before, now it returns `error'.

Close issues for `bigint`:
1) #246 
2) #243
3) #244
4) #250
5) #252

2024-10-04 08:14 UTC, sylwiaszunejko requested changes

2024-10-04 08:14 UTC, sylwiaszunejko commented on marshal_5_bigint_test.go
> +	bigint "github.com/gocql/gocql/marshal/bigint"
same as before

2024-10-04 13:04 UTC, illia-li commented on marshal/bigint/marshal_utils.go
> +package smallint
Fixed.

2024-10-04 13:04 UTC, illia-li commented on marshal/bigint/marshal.go
> +package smallint
Fixed.

2024-10-04 13:04 UTC, illia-li commented on marshal/bigint/unmarshal.go
> +package smallint
Fixed.

2024-10-04 13:04 UTC, illia-li commented on marshal/bigint/unmarshal_utils.go
> +package smallint
Fixed.

2024-10-04 13:04 UTC, illia-li commented on marshal_5_bigint_fails_test.go
> +	bigint "github.com/gocql/gocql/marshal/bigint"
Fixed.

2024-10-06 12:57 UTC, illia-li commented
Please take a look again

2024-10-07 06:42 UTC, sylwiaszunejko approved these changes
for me it LGTM, @dkropachev could you take a look?

2024-10-07 21:09 UTC, illia-li commented on marshal.go
> +		retBytes, err = marshalCounter(info, value)
I didn't see these changes.
Renamed into `marshalBigIntOld`.

2024-10-08 10:11 UTC, dkropachev approved these changes

2024-10-08 10:11 UTC, merged