Fix `timestamp` fixed `zero data` serialization for `time.Time`
scylladb/gocql pull request #375
Opened 2024-12-12 21:46 UTC by illia-li

Changes:
1) Unmarshalling `zero data` into `time.Time` return `time.Time{}` before, now returns `zeroTimestamp`.
2) Marshalling `time.Time{}` return `zero data` before, now returns `nil data`.
3) Added range matching check for the `time.Time` on marshalling and relevant tests.

2024-12-12 22:56 UTC, dkropachev requested changes

2024-12-12 22:56 UTC, dkropachev commented on cassandra_test.go
> +	if !timeVal.IsZero() && !timeVal.Equal(time.UnixMilli(0).UTC()) {
Please make a const of it.

2024-12-12 22:56 UTC, dkropachev commented on serialization/timestamp/unmarshal_utils.go
> +			*v = zeroTimestamp.UTC()
it should be in UTC already

2024-12-12 22:56 UTC, dkropachev commented on serialization/timestamp/unmarshal_utils.go
> +			val := zeroTimestamp.UTC()
it should be in UTC already

2024-12-13 15:35 UTC, illia-li commented on serialization/timestamp/unmarshal_utils.go
> +			*v = zeroTimestamp.UTC()
Fixed

2024-12-13 15:35 UTC, illia-li commented on serialization/timestamp/unmarshal_utils.go
> +			val := zeroTimestamp.UTC()
Fixed

2024-12-13 16:20 UTC, illia-li commented on cassandra_test.go
> +	if !timeVal.IsZero() && !timeVal.Equal(time.UnixMilli(0).UTC()) {
Done

2024-12-13 17:15 UTC, dkropachev approved these changes

2024-12-13 17:15 UTC, merged

2025-04-10 18:36 UTC, Fornax96 commented
Whoa this is a huge breaking change! 1970-01-01 is absolutely not equal to zero time in Go. This breaks the `IsZero()` method on the Time struct for timestamps which were read from the database. And there's no easy way to check if a timestamp is zero now.

This caused some significant bugs in my codebase, as I relied on zero timestamps for all kinds of functionality.

While 1970-01-01 is equal to the unix timestamp, it holds no special meaning in Go, it's just a timestamp. Can this change be reverted? I won't be able to upgrade while unmarshaling zero times is broken.

2025-04-10 20:05 UTC, dkropachev commented
> Whoa this is a huge breaking change! 1970-01-01 is absolutely not equal to zero time in Go. This breaks the `IsZero()` method on the Time struct for timestamps which were read from the database. And there's no easy way to check if a timestamp is zero now.
> 
> This caused some significant bugs in my codebase, as I relied on zero timestamps for all kinds of functionality.
> 
> While 1970-01-01 is equal to the unix timestamp, it holds no special meaning in Go, it's just a timestamp. Can this change be reverted? I won't be able to upgrade while unmarshaling zero times is broken.

I am sorry it happened to you.
But unfortunatelly it should be like this, timestamp is encoded as integer of mseconds since `1970-01-01 00:00:00 +0000 UTC`,  so `timestamp(0)` is `1970-01-01 00:00:00 +0000 UTC` and it is not `.IsZero()`.

Can you please explain your case and we can figure out what we can do with it.

2025-04-10 20:22 UTC, Fornax96 commented
I opened an issue for it #419.

The problem I have now is that all the values that were previously saved as a zero timestamp are now read as 1970-01-01, which is a completely different date. It can't be the right behaviour for a database to return different values than the ones I wrote to it.

2025-04-10 23:15 UTC, jwueller commented
> I am sorry it happened to you. But unfortunatelly it should be like this, timestamp is encoded as integer of mseconds since `1970-01-01 00:00:00 +0000 UTC`, so `timestamp(0)` is `1970-01-01 00:00:00 +0000 UTC` and it is not `.IsZero()`.

I might be misunderstanding this, but changing how data is written vs read without an explicit opt-in is a **breaking change** that **silently corrupts data!** That's probably _the_ worst thing that can happen when working with a database!

Even if this is desired behavior, it needs a _big_ flashing warning if the _default behavior_ changes. I suggest you roll this back immediately, tell everyone that used the new version to check their data and/or restore backups, and revisit how you can safely roll things out in the future.

2025-04-11 12:24 UTC, illia-li commented
Data corruption from the driver side is possible only if serialization does not match deserialization. 
This point on the driver side has been tested. 
Another thing is the client side code, it seems we need to eradicate the hope that critical points there are covered by tests.