Let retry policy to decide about non idempotent queries
scylladb/gocql pull request #376
Opened 2024-12-18 17:14 UTC by sylwiaszunejko

This PR:
* Makes Conn.exec to include a flag into error that signals that query could have been actually executed, despite error been recieved.
* Picks up this error in queryExecutor.do and if query is not idempotent wrap it with user-facing error that would signal to retry policy and to user that this non idempotent query was failed but could be actually executed.

Fixes: #326, #331

2024-12-20 11:53 UTC, dkropachev requested changes
On next PR let's do some heuristic from server error, take a look at [parseErrorFrame](https://github.com/scylladb/gocql/blob/fc36a673eeb41e729466b3a115cb99bba0047343/frame.go#L607-L735)

2024-12-20 13:35 UTC, sylwiaszunejko commented on query_executor.go
> +						return iter
wrap what exactly? we do not have an error here or if error is there there is no rt to consider if query should be retried or not

2024-12-20 13:47 UTC, sylwiaszunejko commented on query_executor.go
> +						return iter
but we don't consider rt here

2024-12-20 14:59 UTC, dkropachev commented on query_executor.go
> +						return iter
Yes, but it is not for RT only, it is only for user to know.

2024-12-20 14:59 UTC, dkropachev commented on query_executor.go
> +						return iter
My bad. Nothing to wrap up here, indeed.

2024-12-20 17:56 UTC, sylwiaszunejko commented on query_executor.go
> +						return iter
but we return a iter here, should I wrap iter.err in PotentiallyExecutedNotIdempotentError?

2024-12-20 17:59 UTC, sylwiaszunejko commented on query_executor.go
> +						return iter
I pushed new version with this changed, but tbh I am not sure about that part

2024-12-23 13:38 UTC, dkropachev requested changes

2024-12-23 13:38 UTC, dkropachev commented on query_executor.go
> +					switch iter.err {
It won't work, we wrap it in `QueryError`, now we need to do `errors.Is` instead

2024-12-23 14:37 UTC, sylwiaszunejko commented on conn.go
> +type PotentiallyExecutedNotIdempotentError struct {
not sure why having IsQueryLWT would be helpful?

2024-12-23 14:55 UTC, dkropachev requested changes

2024-12-23 14:55 UTC, dkropachev commented on policies.go
> +		if executedErr.potentiallyExecuted && !executedErr.isIdempotent {
Don't use them directly, have getters please.

2024-12-23 17:02 UTC, sylwiaszunejko commented on policies.go
> +		if executedErr.potentiallyExecuted && !executedErr.isIdempotent {
done

2024-12-30 10:58 UTC, sylwiaszunejko commented
@dkropachev ping

2024-12-30 13:57 UTC, sylwiaszunejko commented on query_executor.go
> +		}
with this change in this case if rt = nil we would not retry, but it is not in line with current behavior, when we retry on the next host, I would change `getShouldRetry(qry)` to just `true` in first three cases

2024-12-30 18:09 UTC, sylwiaszunejko commented
@dkropachev I applied changes suggested by you and split everything into separate commits

2024-12-31 13:34 UTC, dkropachev commented
@sylwiaszunejko , I have found one more issue and fixed it in the code, pushing one more commit, please review it.

2024-12-31 13:47 UTC, sylwiaszunejko commented
> @sylwiaszunejko , I have found one more issue and fixed it in the code, pushing one more commit, please review it.

I incorporated this change into commits, but in this case I think simple comment to consider changing return type to RetryType instead of bool would make perfect sense and I could actually implement that myself and save you some time

2024-12-31 14:10 UTC, dkropachev commented
> > @sylwiaszunejko , I have found one more issue and fixed it in the code, pushing one more commit, please review it.
> 
> I incorporated this change into commits, but in this case I think simple comment to consider changing return type to RetryType instead of bool would make perfect sense and I could actually implement that myself and save you some time

Having this change in a separate commit makes it confusing because reaction on say, context.Canceled and on ErrHostDown are not preserved in between.

2024-12-31 14:17 UTC, sylwiaszunejko commented
@dkropachev does it look better now? Or did I miss some parts when trying to separate the changes into small separate commits?

2024-12-31 17:55 UTC, dkropachev approved these changes

2024-12-31 17:55 UTC, merged